# Generated by Django 6.0.6 on 2026-06-28 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeeproduct',
            name='roast_level',
            field=models.CharField(choices=[('light', 'Light'), ('medium', 'Medium'), ('dark', 'Dark')], max_length=10),
        ),
    ]
